### ISSUE TITLE
Does not compile with FreeBSD c++ compiler

### ISSUE THREAD

**Issue by bgalbrecht** [jruby/jruby-launcher#19]
This fails because argparser.cpp line 138 is using the wrong value for a C string terminator:
 char sep[2] = { FILE_SEP, NULL };
should be
 char sep[2] = { FILE_SEP, '\0' };

hera% gmake
gmake -f inc/Makefile-rules.mk CONF=unix SUBPROJECTS= .build-conf
gmake[1]: Entering directory '/home/bruce/jruby-launcher'
gmake -f inc/Makefile-rules.mk jruby
gmake[2]: Entering directory '/home/bruce/jruby-launcher'
mkdir -p build/unix/FreeBSD
rm -f build/unix/FreeBSD/argparser.o.d
c++ -O2 -Wall    -c argparser.cpp -MMD -MP -MF build/unix/FreeBSD/argparser.o.d -o build/unix/FreeBSD/argparser.o
argparser.cpp:138:35: error: cannot initialize an array element of type 'char' with an rvalue of type
      'nullptr_t'
        char sep[2] = { FILE_SEP, NULL };
                                  ^~~~
/usr/include/sys/_null.h:35:14: note: expanded from macro 'NULL'
#define NULL    nullptr
                ^~~~~~~
argparser.cpp:252:17: warning: unused variable 'buffer' [-Wunused-variable]
    struct stat buffer;
                ^
1 warning and 1 error generated.

Older versions of gcc just issue a warning and convert the NULL to a 0 ('\0'):
g++ -O2 -Wall    -c argparser.cpp -MMD -MP -MF build/unix/FreeBSD/argparser.o.d -o build/unix/FreeBSD/argparser.o
argparser.cpp: In member function 'bool ArgParser::initPlatformDir()':
argparser.cpp:138:40: warning: converting to non-pointer type 'char' from NULL [-Wconversion-null]
         char sep[2] = { FILE_SEP, NULL };
                                        ^

**Comment by bgalbrecht** [comment]
I have a modification for argparser.cpp to fix this, but I don't have permission to push it to the repository.

**Comment by enebo** [comment]
@bgalbrecht can you provide a pull request for this.  I can fix it but it looks like it is possible you may have other FreeBSD fixes.  I can also just fix this for you if you do not have time for this...

**Comment by bgalbrecht** [comment]
Enebo merged the pull request #21
