### ISSUE TITLE
Make should use default c/c++ compiler

### ISSUE THREAD

**Issue by bgalbrecht** [jruby/jruby-launcher#20]
On FreeBSD, the default compilers are cc/c++, and this is true on Ubuntu as well.  The FreeBSD packages for gcc install it under g++5, g++6, g++7, etc. so in order to get this to build on FreeBSD, I have to create a symlink for g++.  If inc/Makefile-conf.mk were modified so that CC, CCC, CXX were not overriden, at least for FreeBSD, (and my other issue fixed), this would be a painless install for FreeBSD.

I have a modification for inc/Makefile-conf.mk that skips the CC/CCC/CXX overrides just for FreeBSD, but I do not have the permissions to push it to the repository.

**Comment by enebo** [comment]
@bgalbrecht I just deleted those defaults.  I can say CC/CXX are fine on windows and linux.  I could run a quick test on macos, but we can deal with the exceptions when we find them and assume the 
common sense default (e.g. Make defines the right values for us).

@bgalbrecht Can you verify this is resolves the problem for you?
